---
name: Lint code

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches-ignore: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Lint code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ANSIBLE: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_JSCPD: false
          VALIDATE_CPP: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_GITHUB_ACTIONS: false
          FILTER_REGEX_EXCLUDE: (attic/.*|datasets/face_id/.*\.md|\.github/workflows/.*\.yml)

      - name: Install codespell
        run: pip install codespell tomli

      - name: Run codespell
        run: codespell

      # - name: Install markdown-lint-check
      #   run: npm install -g markdown-link-check

      # - name: Run markdown-lint-check
      #   run: find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check -a 0 -p -v -r
